version: '3'
services:
  web:
    build: .
    command: python3 ./manage.py runserver 0.0.0.0:8000
    ports:
    - 8000:8000
    volumes:
    - .:/data
    depends_on:
    - db
    environment:
     DATABASE_URL: postgres://postgres@db/postgres

  db:
    image: postgres:12.2
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
